apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260603-210222-9a0tm9x409ey-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260603-210222-9a0tm9x409ey.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260603-210222-9a0tm9x409ey-service
            port:
              number: 80
